use crate::config::Config;
use pulldown_cmark::{Event, Parser, Tag};
use std::collections::BTreeSet;
use std::fmt::Write as _;

pub async fn run(cfg: &Config, source: Option<&str>, category: &str) -> anyhow::Result<()> {
    let cat = cfg.category(category)?;
    let source = source
        .map(str::to_string)
        .or_else(|| cat.seed_source.clone())
        .ok_or_else(|| anyhow::anyhow!("no seed source: pass an argument or set categories.{category}.seed_source"))?;
    let markdown = load_source(&source).await?;
    let repos = parse_repos(&markdown);

    let dir = &cat.data_dir;
    std::fs::create_dir_all(dir)?;
    let out = dir.join("repos.yaml");
    let mut buf = String::from("# Generated by `scorecards seed`. Do not edit by hand.\nrepos:\n");
    for r in &repos {
        let _ = writeln!(buf, "  - {r}");
    }
    std::fs::write(&out, buf)?;
    println!("wrote {} repos to {}", repos.len(), out.display());
    Ok(())
}

async fn load_source(source: &str) -> anyhow::Result<String> {
    if source.starts_with("http://") || source.starts_with("https://") {
        Ok(reqwest::get(source).await?.error_for_status()?.text().await?)
    } else {
        Ok(std::fs::read_to_string(source)?)
    }
}

/// Extract unique `owner/name` repo slugs from awesome-list markdown.
/// Sorted output keeps regeneration byte-identical (spec: stable, diff-friendly).
pub fn parse_repos(markdown: &str) -> Vec<String> {
    let mut slugs: BTreeSet<String> = BTreeSet::new();
    for event in Parser::new(markdown) {
        if let Event::Start(Tag::Link { dest_url, .. }) = event
            && let Some(slug) = github_slug(&dest_url)
        {
            slugs.insert(slug);
        }
    }
    slugs.into_iter().collect()
}

/// Normalize a URL to a lowercase `owner/name` slug, or None if not a GitHub repo URL.
fn github_slug(url: &str) -> Option<String> {
    let u = url::Url::parse(url).ok()?;
    if !u.host_str()?.eq_ignore_ascii_case("github.com") {
        return None;
    }
    let parts: Vec<&str> = u.path_segments()?.filter(|s| !s.is_empty()).collect();
    if parts.len() < 2 {
        return None;
    }
    let (owner, repo) = (parts[0], parts[1]);
    // Skip non-repo github pages (topics, marketplace, orgs landing, ...)
    const NOISE: &[&str] = &[
        "topics", "marketplace", "sponsors", "features", "pricing", "login", "signup",
        "settings", "notifications", "explore", "trending", "collections", "events",
        "about", "search", "orgs",
    ];
    if NOISE.contains(&owner.to_ascii_lowercase().as_str()) {
        return None;
    }
    let repo = repo.strip_suffix(".git").unwrap_or(repo);
    if repo.is_empty() {
        return None;
    }
    Some(format!("{}/{}", owner.to_lowercase(), repo.to_lowercase()))
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_and_normalizes() {
        let md = r#"
# List
- [Foo](https://github.com/Owner/Foo) — thing
- [Bar](https://github.com/owner/bar.git)
- [Baz](http://github.com/owner/baz/)
- [Deep](https://github.com/owner/deep/tree/main/lua)
- [Frag](https://github.com/owner/frag#readme)
- [Query](https://github.com/owner/query?tab=readme)
"#;
        assert_eq!(
            parse_repos(md),
            vec![
                "owner/bar",
                "owner/baz",
                "owner/deep",
                "owner/foo",
                "owner/frag",
                "owner/query"
            ]
        );
    }

    #[test]
    fn skips_non_github_and_noise() {
        let md = r#"
- [GL](https://gitlab.com/owner/repo)
- [SH](https://git.sr.ht/~owner/repo)
- [Topic](https://github.com/topics/neovim)
- [Site](https://example.com/github.com/owner/tricky)
"#;
        assert!(parse_repos(md).is_empty());
    }

    #[test]
    fn dedupes_case_insensitively() {
        let md = "- [A](https://github.com/Foo/Bar)\n- [B](https://github.com/foo/bar/)";
        assert_eq!(parse_repos(md), vec!["foo/bar"]);
    }

    #[test]
    fn bare_owner_only_is_skipped() {
        let md = "- [Org](https://github.com/someorg)";
        assert!(parse_repos(md).is_empty());
    }

    #[test]
    fn deterministic_output() {
        let md = "- [B](https://github.com/o/b)\n- [A](https://github.com/o/a)";
        assert_eq!(parse_repos(md), parse_repos(md));
        assert_eq!(parse_repos(md)[0], "o/a");
    }
}
